# Generated by Django 6.0.2 on 2026-02-23 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dateTimeOfCreation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('imageUrl', models.ImageField(blank=True, null=True, upload_to='discussions/')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('userId', models.CharField(max_length=30)),
                ('communityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Discussion.community')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm', models.TextField()),
                ('dateTimeOfCreation', models.DateTimeField(auto_now_add=True)),
                ('userId', models.CharField(max_length=30)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Discussion.comment')),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaries', to='Discussion.discussion')),
            ],
        ),
    ]
