# Generated by Django 6.0.2 on 2026-03-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0002_rename_datetimeofcreation_comment_creationdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='imageUrl',
            field=models.ImageField(blank=True, null=True, upload_to='communities/'),
        ),
    ]
